default_platform(:ios)

platform :ios do
  desc "Run tests for iOS"
  lane :test do
    sync_code_signing(
      type: "development", 
      readonly: true, 
      platform: "ios"
    )
    run_tests(
      project: 'IBProxy.xcodeproj', 
      scheme: 'IBProxyKit iOS', 
      code_coverage: true
    )
  end
end

platform :macos do
  desc "Run tests for macOS"
  lane :test do
    if is_ci
      create_keychain(
        name: "CI",
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
      match(
        type: "development",
        readonly: true,
        keychain_name: "CI",
        keychain_password: ENV["MATCH_PASSWORD"],
        platform: "macos",
        skip_provisioning_profiles: true
      )
      sh("security list-keychains -d user")
      sh("security default-keychain -d user")
      sh("security find-identity -v -p codesigning CI")
    else
      sync_code_signing(
        type: "development", 
        readonly: true, 
        platform: "macos", 
        skip_provisioning_profiles: true
      )
    end

    run_tests(
      project: 'IBProxy.xcodeproj', 
      scheme: 'IBProxyKit macOS', 
      code_coverage: true
    )
  end
end