default_platform(:ios)

platform :ios do
  desc "Run tests for iOS"
  lane :test do
    run_tests(project: 'IBProxy.xcodeproj', scheme: 'IBProxyKit iOS', code_coverage: true)
  end
end

platform :mac do
  desc "Run tests for macOS"
  lane :test do
    run_tests(project: 'IBProxy.xcodeproj', scheme: 'IBProxyKit macOS', code_coverage: true)
  end
end