name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  testMacOS:
    name: Run iOS tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run Test
      run: xcodebuild -project IBProxy.xcodeproj -scheme "IBProxyKit iOS" -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.6' build test

  testiOS:
    name: Run macOS tests
    runs-on: macOS-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install certificates
      run: | 
        fastlane match development
      env:
        MATCH_PASSWORD: ${{ secrets.MATCH_PASS }}
    - name: Run Test
      run: xcodebuild -project IBProxy.xcodeproj -scheme "IBProxyKit macOS"  -sdk macosx build test
    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
